module.exports = {
     leanTermsList : [
        {id: 1, term: '6s' , answer: 'study, sort, set in order, standardize, and sustain'}, 
        {id: 2, term: 'A3 report', answer: 'A problem solving tool named after the international paper size (A3) approximately 11x17. Developed to fit on this size of paper as a guide to keep all steps as concise as possible. You’re not working on the root cause of the problem if you can’t fit on this size sheet.'},
         {id: 3, term: 'Andon', answer: 'A visual light used to show the current status of a machine or process.'}, 
         {id: 4, term: 'Autonomation', answer: 'English word for jidoka is autonomation, based on autonomous and automation. Others call it intelligent automation, and again others describe it as automation with a human touch.'},
          {id: 5, term: 'Current State', answer: 'Current condition of anything. How something is currently being done.'},
          {id: 6, term: 'Cycle Time', answer: 'The time it takes a product to be built or moved within its process (“The process” is typically defined as the smallest reasonable timed event). There is no speed limit for cycle time, it may be readily improved upon, but must be sustainable, not a singular event.'},
          {id: 7, term: 'Defects', answer: 'Waste of inspection, repair, and scrapping of material to which value has already been added.'},
          {id: 8, term: 'FIFO', answer: 'First in, first out.'},
          {id: 9, term: 'Five Whys', answer: 'Asking five why questions to get to the root cause of a problem.'},
          {id: 9, term: 'Flow', answer: 'Move or process in a forward motion.'},
          {id: 11, term: 'Future state', answer: 'The condition we imagine something can be in once changes have taken place.'},
          {id: 12, term: 'Gemba', answer: '“The real place” the place where work occurs.'},
          {id: 13, term: 'Genchi Gembutsu', answer: '“Go and see.” Go to the real source for first-hand knowledge. Immerse yourself in the process at the gemba to get full comprehension before making decisions.'},
          {id: 14, term: 'Hai', answer: ' “I accept the challenge.”'},
          {id: 15, term: 'Hansei', answer: ' “Reflection”. Reflect on what went right or what went wrong. Make changes if needed and try something else.'},
          {id: 16, term: 'Heijunka', answer: 'A process to help manage production by leveling peaks and valleys of customer demand.'},
          {id: 17, term: 'Hoshin Kanri', answer: 'A method for ensuring that the strategic goals of a company drive progress and action at every level within that company. This eliminates the waste that comes from inconsistent direction and poor communication. We use publicly declared goals on our Hoshin Kanri Boards.'},
          {id: 18, term: 'Jidoka', answer: 'The concept of stopping the process automatically if there are problems or abnormalities. “Autonomation”.'},
          {id: 19, term: 'JIT (Just In Time)', answer: 'Product delivered to customer or next process at exactly the moment they need it. Not one moment too soon, not moment too late.'},
          {id: 20, term: 'Kaizen', answer: 'Many small changes for the better, created by the people that do the work.'},
          {id: 21, term: 'Kanban', answer: 'A visual system that shows you to replace what has been consumed.'},
          {id: 22, term: 'Kata', answer: 'The practice of kata, is the act of practicing a pattern so it becomes second nature. Having a shared understanding of how you want to improve. (Our kata, the In the ditch way)'},
          {id: 23, term: 'KPI: (Key Performance Indicators)', answer: 'These are ways to measure if we are winning or losing by monitoring performance objectives.'},
          {id: 24, term: 'Lean', answer: 'Creating value by minimizing waste. Lean is centered on making obvious what adds value by reducing everything else. "Value" is any action or process that a customer would be willing to pay for.'},
          {id: 25, term: 'Muda', answer: 'Waste any step or process that does not add value in the eyes of the customer.'},
          {id: 26, term: 'Over-production', answer: 'Waste of making too much, too soon, too fast compared to the needs of the next process. Considered one of the worst wastes of company profits.'},
          {id: 27, term: 'PDCA (Plan-Do-Check-Act)', answer: 'A problem-solving method that leads you through continuous improvement cycles.'},
          {id: 28, term: 'Poka-yoke', answer: 'Device or procedure designed to help prevent the generation of most defects.'},
          {id: 29, term: 'Push system', answer: 'Building products that you have no customer for and trying to push those products onto the customer or next process.'},
          {id: 30, term: 'Pull system', answer: 'Building products at the pull of the customer; only building exactly what the customer wants, when they want it.'},
          {id: 31, term: '“Pull the rope”', answer: 'To stop a machine or process any time a problem occurs.'},
          {id: 32, term: 'Red team', answer: 'A team of people from various departments well versed in lean problem-solving techniques that people can call to help coach and mentor them through solving their problem within the company. They have the ability to get things done.'},
          {id: 33, term: 'Socratic method', answer: 'Asking questions to stimulate critical thinking and to illuminate ideas.'},
          {id: 34, term: 'Shadow board', answer: 'Location for tools which the tools location is clearly defined by the shadow of the tool.'},
          {id: 35, term: 'Shu Ha Ri', answer: 'Learning cycle to master a skill of a skill of a process.'},
          {id: 36, term: 'Shu', answer: '"Follow our Processes and Protect Our Kata" Novice Learning fundamentals and techniques with help from a mentor.'},
          {id: 37, term: 'Ha', answer: '"Break Away" Proficient Able to perform at a high level without the need of a mentor.'},
          {id: 38, term: 'Ri', answer: '"Freedom to Create" Master Mastery of our kata to the point where you become the mentor.'},
          {id: 38, term: 'Stakeholder', answer: 'Anyone who relies on the company. Such as a supplier, customer, communities, and employees.'},
          {id: 40, term: 'Supermarket', answer: 'Area where items are stored in a defined, dedicated place and are continually replaced.'},
          {id: 41, term: 'Value added', answer: 'Anything that adds value in the eyes of the customer. Something that the customer would be willing to pay more for.'},
          {id: 42, term: '"T" type leader', answer: 'A “T” type leader grows like a tree. It starts with the roots. You gain deep-rooted understanding and experience in your Gemba (the long stem of the “t”). Then you will broaden your leadership skills by branching out to gain exposure across departments and sometimes even the entire organization (the top horizontal part of the “T”). Group leaders must be “T” type leaders.'},
          {id: 43, term: 'Takt time:', answer: 'The rate at which product should be produced to satisfy customer and company needs. Takt time is a governor of time. Building faster than the takt time is overproduction and should be avoided. Takt time should only be changed by a group decision.'},
          {id: 44, term: 'Teach and learn', answer: 'As you teach someone, they then have an obligation in our organization to teach others. Teach and learn, learn and teach. We want to teach the world it is a part of our very core.'},
          {id: 45, term: 'Theory of constraints (TOC)', answer: 'Approach to capacity improvement by focusing on improving the constraint or bottleneck.'},
          {id: 46, term: 'Toyota production system (TPS)', answer: 'A manufacturing strategy developed by Toyota motor corporation of Japan over a period of many years. TPS focuses on the complete elimination of waste from the manufacturing process.'},
          {id: 47, term: 'Value stream mapping', answer: 'A tool used to visually map the flow of production. Shows the current and future state of processes in a way that highlights opportunities for improvement.'},
          {id: 48, term: 'WIP', answer: 'Work in process - adding value to the product that the customer is not willing to pay for yet.'},
    ],
    
     eightWastesList : [
        {id: 1, term: '1. Overproduction', answer: 'To produce sooner, faster, or in greater quantities than customer demands.'},
        {id: 2, term: '2. Inventory', answer: 'Raw material, work in process, or finished goods which is not having value added to it.'},
        {id: 3, term: '3. Waiting', answer: 'People or parts that wait for a work cycle to be completed.'},
        {id: 4, term: '4. Motion', answer: 'Unnecessary movement of people, parts or machines within a process.'},
        {id: 5, term: '5. Transportation', answer: 'Unnecessary movement of people or parts between processes.'},
        {id: 6, term: '6. Defects:', answer: 'Not right the first time. Repetition or correction of a process. Scrap, rework and defects.'},
        {id: 7, term: '7. Over Processing', answer: 'Processing beyond the standard required by the customer.'},
        {id: 8, term: '8. Talent', answer: 'Underutilizing people’s talents, skills, and knowledge.'},
    ],
}

